# Generated by Django 2.1.3 on 2018-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_server_ping_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='core',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='server',
            name='ram',
            field=models.IntegerField(default='512'),
        ),
    ]
