# Generated by Django 2.1.3 on 2018-11-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20181123_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_ok', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('status', models.CharField(max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Server')),
            ],
        ),
    ]
