# Generated by Django 2.1.3 on 2018-12-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_phonetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneTime',
        ),
    ]
