# Generated by Django 2.1.3 on 2018-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_delete_phonetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayIndex', models.IntegerField()),
                ('dayName', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='phonetime',
            name='dayOfTheWeek',
            field=models.ManyToManyField(to='panel.WeekDay'),
        ),
    ]
