# Generated by Django 2.1.3 on 2018-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_on_reseller', models.CharField(max_length=200)),
                ('server_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ssh_username', models.CharField(blank=True, max_length=200, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=200, null=True)),
                ('root_permissions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
    ]
