# Generated by Django 2.1.3 on 2018-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
    ]
