# Generated by Django 2.1.3 on 2018-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20181207_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='PhoneTime',
            field=models.ManyToManyField(to='panel.PhoneTime'),
        ),
    ]
