# Generated by Django 2.1.3 on 2018-12-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_server_phonetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_username',
        ),
    ]
